version: '3.1'

networks:
  frontend:
    external: true
  backend:

volumes:
  nginx_proxy_data:
  nginx_proxy_letsencrypt:
  nginx_proxy_db:

secrets:
  nginxproxymanager_db_password:
    external: true
  nginxproxymanager_db_root_password:
    external: true

services:

  nginx-proxy-manager-app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: 'nginx-proxy-manager-db'
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: 'npm'
      DB_MYSQL_PASSWORD__FILE: /run/secrets/nginxproxymanager_db_password
      DB_MYSQL_NAME: 'npm'
    volumes:
      - nginx_proxy_data:/data
      - nginx_proxy_letsencrypt:/etc/letsencrypt
    secrets:
      - nginxproxymanager_db_password
    networks:
      - frontend
      - backend

  nginx-proxy-manager-db:
    image: 'jc21/mariadb-aria:latest'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD__FILE: /run/secrets/nginxproxymanager_db_root_password
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD__FILE: /run/secrets/nginxproxymanager_db_password
    volumes:
      - nginx_proxy_db:/var/lib/mysql
    secrets:
      - nginxproxymanager_db_password
      - nginxproxymanager_db_root_password
    networks:
      - backend
