name: nginxproxymanager

networks:
   frontend:
      external: true
   backend:

secrets:
   db_password:
      file: ./secrets/db_password.txt
   db_root_password:
      file: ./secrets/db_root_password.txt

services:

   app:
      image: docker.io/jc21/nginx-proxy-manager:2
      privileged: true
      restart: unless-stopped
      depends_on:
         - db
      ports:
         - 80:80
         - 81:81
         - 443:443
      environment:
         DB_MYSQL_HOST: 'db'
         DB_MYSQL_PORT: 3306
         DB_MYSQL_USER: 'npm'
         DB_MYSQL_PASSWORD__FILE: /run/secrets/db_password
         DB_MYSQL_NAME: 'npm'
      volumes:
         - 'data:/data'
         - 'letsencrypt:/etc/letsencrypt'
      secrets:
         - db_password
      networks:
         - frontend
         - backend

   db:
      image: docker.io/jc21/mariadb-aria:10.11.5
      privileged: true
      restart: unless-stopped
      environment:
         MYSQL_ROOT_PASSWORD__FILE: /run/secrets/db_root_password
         MYSQL_DATABASE: 'npm'
         MYSQL_USER: 'npm'
         MYSQL_PASSWORD__FILE: /run/secrets/db_password
      volumes:
         - 'db:/var/lib/mysql'
      secrets:
         - db_password
         - db_root_password
      networks:
         - backend

volumes:
   db:
   data:
   letsencrypt:
