name: portainer

networks:
   frontend:
      external: true

services:

   portainer:
      image: docker.io/portainer/portainer-ce:2.20.0
      container_name: portainer
      privileged: true
      ports:
         - 9000:9000
         - 9443:9443
      volumes:
         - data:/data
         - /var/run/docker.sock:/var/run/docker.sock
      networks:
         - frontend

volumes:
   data:
